name: Deploy Postman Collection

on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Npm Install
        run: npm ci

      - name: Deploy Postman collection
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: node deployPostmanCollection.js
